### ISSUE TITLE
Is it possible to use it on android? 

### ISSUE THREAD

**Issue by mat-os** [aquarterofpixel/Raymarching#1]
Hello 👋 
What do you think, why is ray marching stop working when i change build target to "Android"? Maybe you know how to fix it?
Amazing asset btw, you should sell it on asset store i think)

**Comment by adcimon** [comment]
Hi!

The project doesn't use any specific graphic feature incompatible with Android (just vertex and fragment shaders). The drawback of this solution is the performance, is a very intensive (almost brute-force) approach to render signed distance functions. It was my entry point project to the amazing world of implicit surfaces.

If you want to use this kind of approach for modeling, games, etc. I recommend you more professional solutions like MudBun or Clayxels, both in the Unity Asset Store.

**Comment by mat-os** [comment]
Oh, Thank you very much for the answer! 
Implicit surfaces is really cool technology, thanks for your help and good luck with your work 👍
